### ISSUE TITLE
Grow v0.0.67 segfault on linux

### ISSUE THREAD

**Issue by drGrove** [grow/grow#339] opened 2016-11-05 17:56 UTC
There appears to be an issue in the linux build of grow for v0.0.67 causing a segfault core dump. Below are the details of the systems that this has been attempted on.

Python Version(s):

Arch
  - 2.7.12
  - 3.5.2

Ubuntu
  - 2.7.12

Tested Linux Systems:
- Arch linux -> 4.8.6-1-ARCH
- Ubuntu 16.04.1 LST -> 4.4.0-28-generic

Attempted install types:
- pip
- build from souce
- unzip linux binary

Terminal Output:
(Arch Linux) 31169 segmentation fault (core dumped) grow --help
(Ubuntu) 16528 segmentation fault (core dumped) grow --help

Current solution:
Install grow v0.0.66

**Comment by drGrove** [comment] 2016-11-12 03:08
I also tested this via curl on a brand new ubuntu instance on Digital Ocean, it also fails with a segfault:
$ uname -r 
# 4.4.0-45-generic

**Comment by Zoramite** [comment] 2016-11-14 20:33
Duplicate of #305

**Closed by Zoramite** 2016-11-14 20:33 UTC
