### ISSUE TITLE
Clarify `grow extract --localized` behaviour

### ISSUE THREAD

**Issue by stucox** [grow/grow#204] opened 2016-04-28 17:38 UTC
cc @jeremydw, @willsb3 & @matthewhall 

In attempting to fix #157, I found various other cases of `grow extract --localized` which didn’t act as I’d expect.

These all relate to strings being extracted for locales for which they aren’t needed, which:

(a) Makes `grow filter` report translations are missing when they aren’t, hence making it harder to identify translations which _are genuinely_ missing
(b) Creates unnecessary work for translators

The behaviour of `grow extract --localized` isn’t documented on grow.io and doesn’t have very extensive test coverage. It’d be good to clarify exactly which tagged strings in which context should be expected to be extracted into which locales’ message catalogs, get tests in place, and refactor (hopefully simplify) `Catalogs.extract()` to match.

My effort so far:
* In https://github.com/stucox/pygrow/commit/16137fdaae394e47e5af1a330822b3abf0ce248c I increased the test coverage of `Catalogs.extract()`, describing the **current behaviour** (all tests pass on this commit)
* Those cases from [L91](https://github.com/stucox/pygrow/commit/16137fdaae394e47e5af1a330822b3abf0ce248c#diff-d1b59363637d70582c52f59100e5e256R91) onwards represent behaviour **I think is undesirable**
* In https://github.com/stucox/pygrow/commit/9cd889381a9d7e05fa8e5fb85731aa1c067343c5 I changed these to represent the behaviour I think **should be considered correct** — but I think it needs some discussion
* I also attempted to _just_ fix #157 without changing other behaviour, but my “clean” solution would have required many special cases to retain the behaviour I believe is undesirable

These show that in many contexts locale configuration is ignored by `grow extract --localized` and strings are extracted for all locales mentioned anywhere in the pod (not even just those in podspec.yaml) and it’s very hard to ensure strings only appear in the relevant message catalogs.

---

I propose we standardize this as follows:

1. The `/content/` folder is considered a tree of scopes (_pod_ > _collection_ > _document_ > _document part_), such that:
   - Tagged strings are only extracted for the locales declared for the current scope
   - If no locales are declared for the current scope, it assumes the locales of its parent scope
   - YAML, Markdown, HTML and CSV files are all considered “documents” for this purpose and follow the same rule for determining relevant locales
   - Ergo, files with no front matter (including CSVs, which never have front matter) will obviously always assume the collection’s locales (or the pod’s, if no locales are defined in the collection’s blueprint)
2. Tagged strings in `/views/` are simply extracted for all locales named in podspec.yaml

Rule 2 could alternatively state _“all locales named anywhere in the pod”_… there are arguments for/against each, but keen to get general thoughts on the above before launching into that debate.

I’ve omitted `/data/` as I’m not convinced treating it as a special folder is necessary: that isn’t documented anywhere, and it could be argued a `/content/data/` collection (which according to the rules above can also contain translatable CSV files) is more powerful, or alternatively `!g.csv <>` syntax can already be used to bring CSV data into a document (a translatable context).

**Comment by jeremydw** [comment] 2016-04-29 04:56
@stucox Thank you for this thoughtful analysis and your work increasing the test coverage. Reading over this post, I agree with every point you've made in the footer.

And the special case for `/data/` was indeed an urgent and knee-jerk addition to add support for translation of content stored in the `/data/` directory. I agree that this data can be moved to the `/content/` directory (even `/content/data/` as you've described) and that we can add better built-in support for CSV and JSON-formatted content documents.

In response to (2) – I do think it's reasonable to treat every tagged string in `/views/` as something that should be extracted. That seems to me like it's the most obvious behavior. I also think that anything in `/views/` can really be considered UI strings (and not heavy content), and it makes most sense to treat those as globally-available UI strings.

Anyway, I agree moving in the direction you've proposed and I can also confirm that `grow extract --localized` isn't really working as intended. As mentioned this is related to https://github.com/grow/grow/issues/157 and we need to fix that -- it's indeed a bug. It hasn't been very high priority over here so it's been sitting in the queue in favor of things like a tighter translation request workflow (#131) but I agree we should get this fixed up now for the next release.

Here are three things we can do off the top of my head:

1. Fix the behavior of `grow extract --localized`. Add test coverage.
1. Stop treating `/data/` as any sort of special directory and recommend that folks store data in some directory such as `/content/data/` and add test coverage for this scenario.
1. Add a new persistent option to `podspec.yaml`'s `localization` configuration that specifies the default behavior of `grow extract` – so a multi-developer project can simply run `grow extract` and won't have to know they need to specify `--localized`. Any suggestions for this flag option? `localized_catalogs: true`? Looking for something explicit.

Thanks again for your work on this @stucox, appreciate it. Let me know which pieces you'd like to take on and which pieces you'd like to delegate over here!

**Comment by stucox** [comment] 2016-04-29 05:57
Excellent.

To clarify: should global strings (e.g. those in templates) be extracted for ALL locales used anywhere in the pod, or just those listed in the podspec? My vote would be podspec locales only, because:

* IMO it would be expected behaviour
* More explicit
* Potentially avoids terms being extracted for languages they aren't needed for
* To avoid _missing_ locales a term may be required for, those locales could be added to podspec and locale configs adjusted elsewhere to get the correct results

I'll start on #1, as my head's already in it and we have an operational need to fix #157.

Maybe #2 could wait a version, to give anyone using a `/data/` dir time to adapt?

#3 — I'll raise a separate issue.

**Comment by jeremydw** [comment] 2016-04-29 06:09
I think, for now, it should be podspec-only locales as that's consistent
with `grow extract --init` behavior and does not change current behavior –
running `grow extract --init` will not create catalogs for locales that
only appear at the document or collection and in fact it accepts a
`--locale` argument that currently fails when its value is not defined in
podspec, but we could adapt to allow folks to create catalogs manually.

I'd probably recommend getting through those three bullet points first and
then we can look at usage and decide if we want to allow folks to customize
this with either `--locale` or some new configuration option in podspec's
localization section.

Thanks!

**Comment by stucox** [comment] 2016-04-29 07:33
I think the way that I tackle that first one might be slightly different (simpler!) if tagged strings _outside_ `/content/` are only extracted for locales named in the podspec — so I’ll implement it like that.

**Comment by jeremydw** [comment] 2016-04-29 16:22
Sounds good. Thanks Stu. Let me know if you have any questions or would
like to pass a task over. Thanks!

On Fri, Apr 29, 2016 at 12:33 AM, Stu Cox <notifications@github.com> wrote:

> I think the way that I tackle that first one might be slightly different
> (simpler!) if tagged strings *outside* /content/ are only extracted for
> locales named in the podspec — so I’ll implement it like that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/grow/grow/issues/204#issuecomment-215648046>
>



-- 
jeremydw

**Comment by jeremydw** [comment] 2016-08-02 00:18
Before this can be fully closed out, I need to resolve the issue with the legacy `use_podspec_locales` as our new validation is now failing on a site that should be supported. Will add the test case to cover this behavior then close this out.

**Closed** 2016-08-05 21:40 UTC
