### ISSUE TITLE
Improve .bash_profile installer

### ISSUE THREAD

**Issue by somenxavier** [grow/grow#167] opened 2016-01-06 18:57 UTC
Hi,

Please add `export PATH=$PATH:/home/xan/bin` to `.bashrc` or `bash_profile` in addition to
```
# Added by Grow SDK Installer (2016-01-06 19:49:02.856458)
alias grow="/home/xan/bin/grow"
```
Otherwise the `/bin/grow` is not usable.

Thanks,

**Comment by jeremydw** [comment] 2016-07-11 06:57
Marking as a duplicate of #43.

**Closed by jeremydw** 2016-07-11 06:57 UTC
