### ISSUE TITLE
Add --watch option to `grow run` and `grow deploy` to watch and rebuild

### ISSUE THREAD

**Issue by jeremydw** [grow/grow#1049] opened 2020-01-14 22:41 UTC
Similar to features of Hugo and Gatsby, Grow should have a `--watch` flag that watches the working directory and rebuilds (or redeploys) based on changes in the working directory.

Ideally, the rebuild is a partial rebuild and only rebuilds based on changes to the working directory.

This can be used in any scenario that could benefit from observing constant edits to source files and generating output (i.e. local previews with an App Engine proxy, or instant builds based on changes to a git workspace/working directory.

**Comment by Zoramite** [comment] 2020-01-14 23:00
Duplicate of #525 

I think that is was one of the original reasons that I started working on the dependency graph for the content, so we could update only the changed files in the build.

**Closed by Zoramite** 2020-01-14 23:00 UTC
